apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
spec:
  selector:
    app: portfolio
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
    protocol: TCP
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster